import re
import shutil
import time
import uuid
from pathlib import Path
from typing import List

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, Response
from pydantic import BaseModel, Field

router = APIRouter()

# Generated projects live under backend/generated_sites/. The directory is
# created on first save and reused for every run.
GENERATED_SITES_DIR = Path(__file__).resolve().parent.parent / "generated_sites"

# Entry file names a generated site might use, checked in priority order when
# deciding which file to serve for a directory request.
ENTRY_CANDIDATES = ["index.html", "portal.html"]

RUN_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")
WINDOWS_RESERVED_RE = re.compile(
    r"^(con|prn|aux|nul|com[1-9]|lpt[1-9])(\..*)?$", re.IGNORECASE
)


class LocalProjectFile(BaseModel):
    path: str = Field(min_length=1, max_length=200)
    # Generated pages are single HTML files; 5 MB per file is far above any
    # real output and stops runaway payloads from filling the disk.
    content: str = Field(max_length=5_000_000)


class LocalProjectRequest(BaseModel):
    siteName: str | None = None
    files: List[LocalProjectFile] = Field(min_length=1, max_length=200)


class LocalProjectResponse(BaseModel):
    runId: str
    files: int
    url: str


def _safe_relative_parts(raw_path: str) -> Path:
    """Turn an untrusted path into safe relative parts, refusing escapes."""
    cleaned = raw_path.strip().replace("\\", "/")
    # Strip a leading slash so "C:\evil" or "/abs" cannot anchor outside.
    while cleaned.startswith("/"):
        cleaned = cleaned[1:]
    if not cleaned:
        raise ValueError("Empty path")

    parts: List[str] = []
    for segment in cleaned.split("/"):
        segment = segment.strip()
        if segment in ("", "."):
            continue
        if segment == "..":
            raise ValueError("Path traversal is not allowed")
        if WINDOWS_RESERVED_RE.match(segment):
            segment = f"_{segment}"
        parts.append(segment)

    if not parts:
        raise ValueError("Empty path")

    return Path(*parts)


def _resolve_under(root: Path, relative: Path) -> Path:
    candidate = (root / relative).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise ValueError("Path traversal is not allowed") from exc
    return candidate


def _project_root(run_id: str) -> Path:
    if not RUN_ID_RE.match(run_id):
        raise ValueError("Invalid project id")
    root = (GENERATED_SITES_DIR / run_id).resolve()
    try:
        root.relative_to(GENERATED_SITES_DIR)
    except ValueError as exc:
        raise ValueError("Invalid project id") from exc
    return root


def build_readme(site_name: str, file_names: List[str]) -> str:
    pages = "\n".join(f"- `{name}`" for name in file_names)
    return f"""# {site_name}

Generated by UrlToCode.

## Run locally

Open `index.html` in a browser, or serve the folder with any static server:

```bash
python -m http.server 8080
```

## Files

{pages}
"""


@router.post("/api/local-project/save")
async def save_local_project(request: LocalProjectRequest) -> LocalProjectResponse:
    """Persist a generated site to disk and expose it on a local URL.

    The frontend writes the same files into a user-chosen folder via the File
    System Access API; this endpoint mirrors that payload so the site can be
    served immediately without a manual dev server.
    """
    run_id = f"{time.strftime('%Y%m%d-%H%M%S')}-{uuid.uuid4().hex[:8]}"

    root = GENERATED_SITES_DIR / run_id
    written: List[str] = []
    try:
        for file in request.files:
            relative = _safe_relative_parts(file.path)
            target = _resolve_under(root, relative)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(file.content, encoding="utf-8")
            written.append(str(relative).replace("\\", "/"))
    except (OSError, ValueError) as exc:
        # Don't leave a half-written project behind; it would keep being
        # served as if it were complete.
        shutil.rmtree(root, ignore_errors=True)
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    readme_names = [name for name in written if not name.startswith("assets/")]
    (root / "README.md").write_text(
        build_readme(request.siteName or "Generated site", readme_names),
        encoding="utf-8",
    )

    print(f"[LOCAL-PROJECT] Saved {len(written)} files under {run_id}")
    return LocalProjectResponse(runId=run_id, files=len(written), url=f"/generated/{run_id}/")


@router.get("/generated/{run_id}/{file_path:path}")
async def serve_generated_file(run_id: str, file_path: str):
    """Serve a saved project over HTTP so it can be 'run' with one click."""
    try:
        root = _project_root(run_id)
        requested = file_path.rstrip("/") or "index.html"
        full_path = _resolve_under(root, _safe_relative_parts(requested))
    except ValueError:
        return Response(
            content=_error_page("Invalid project path"), media_type="text/html"
        )

    if full_path.is_dir():
        for candidate in ENTRY_CANDIDATES:
            entry = full_path / candidate
            if entry.is_file():
                return _sandboxed_file(entry, "text/html")
        return Response(
            content=_error_page("No index.html in this folder"),
            media_type="text/html",
        )

    if not full_path.is_file():
        return Response(
            content=_error_page("File not found in the generated project"),
            media_type="text/html",
        )

    return _sandboxed_file(full_path, None)


def _sandboxed_file(path: Path, media_type: str | None) -> Response:
    """Serve generated content cut off from the backend's origin.

    Generated HTML is model output of unknown trust; `CSP: sandbox` gives it
    its own opaque origin so it cannot script against the API routes.
    """
    headers = {"Content-Security-Policy": "sandbox allow-scripts allow-forms allow-popups"}
    if media_type:
        return FileResponse(path, media_type=media_type, headers=headers)
    return FileResponse(path, headers=headers)


@router.get("/generated/{run_id}")
async def serve_generated_root(run_id: str):
    return await serve_generated_file(run_id, "index.html")


def _error_page(message: str) -> bytes:
    html = f"""<!DOCTYPE html>
<html>
  <body style="font-family: system-ui, sans-serif; padding: 3rem; color: #334;">
    <h1>UrlToCode</h1>
    <p>{message}</p>
  </body>
</html>"""
    return html.encode("utf-8")
