"""Durable record of a clone run.

A clone is long-running: a thirty-page site can take twenty minutes, and the
crawl data that produced it is gone as soon as the websocket that carried it
closes. Anything that needs to revisit a run afterwards — regenerate one page,
score a page against its original, resume an interrupted clone, list past
clones — needs that data to outlive the request.

Each run is one directory under `clone_runs/`, holding `run.json` with the
crawl result, the parameters and per-page output. Runs are plain files so they
survive a backend restart and can be listed and deleted by the user.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, cast

from crawler.crawler import CrawlPage, CrawlResult

CLONE_RUNS_DIR = Path(__file__).resolve().parent / "clone_runs"

RUN_FILE = "run.json"

# Ids are generated by `new_run_id`, so anything else in a request path is
# either a typo or an attempt to name a different run.
RUN_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")

# Runs are a working cache, not an archive: the user keeps the exported
# project, not our scratch copy. Old runs are pruned so the directory cannot
# grow without bound.
MAX_RUNS = 50
MAX_RUN_AGE_SECONDS = 7 * 24 * 60 * 60

# Page statuses. A page is "pending" until its first generation is attempted.
PENDING = "pending"
GENERATING = "generating"
COMPLETE = "complete"
FAILED = "failed"


@dataclass
class ClonePage:
    """One page of a run: what was asked for, and what came back."""

    path: str
    status: str = PENDING
    code: str = ""
    error: str = ""
    attempts: int = 0
    # Visual agreement with the original, 0..1. Absent until a page is scored.
    fidelity: Optional[float] = None
    updated_at: float = 0.0

    def to_json(self) -> Dict[str, Any]:
        return {
            "path": self.path,
            "status": self.status,
            "code": self.code,
            "error": self.error,
            "attempts": self.attempts,
            "fidelity": self.fidelity,
            "updated_at": self.updated_at,
        }

    @classmethod
    def from_json(cls, data: Dict[str, Any]) -> "ClonePage":
        fidelity = data.get("fidelity")
        return cls(
            path=str(data.get("path", "")),
            status=str(data.get("status", PENDING)),
            code=str(data.get("code", "")),
            error=str(data.get("error", "")),
            attempts=int(data.get("attempts", 0) or 0),
            fidelity=float(fidelity) if isinstance(fidelity, (int, float)) else None,
            updated_at=float(data.get("updated_at", 0.0) or 0.0),
        )


def _empty_params() -> Dict[str, Any]:
    return {}


def _empty_llm() -> Dict[str, Any]:
    return {}


def _empty_pages() -> Dict[str, "ClonePage"]:
    return {}


# Files the run produced beyond its pages - the generated server and the
# captured API mock layer - travel in the same code map as the pages, under
# this prefix and then their own project path. Kept in one prefix rather than
# one per kind so the frontend has a single rule for "not a page".
GENERATED_FILE_PREFIX = "file:"


@dataclass
class CloneRun:
    """A crawl plus everything generated from it."""

    run_id: str
    base_url: str
    stack: str
    # Generation settings, as they were sent. JSON-shaped, so the values are
    # arbitrary and the type says so.
    params: Dict[str, Any] = field(default_factory=_empty_params)
    # Which provider answered. Regenerating a page later must not silently
    # switch models, so the answer is recorded with the run.
    llm: Dict[str, Any] = field(default_factory=_empty_llm)
    crawl: Optional[CrawlResult] = None
    pages: Dict[str, "ClonePage"] = field(default_factory=_empty_pages)
    # Landing page and SQL schema; not crawled pages, so not in `pages`.
    portal: str = ""
    database_schema: str = ""
    # Files the run produced beyond its pages: the generated server and the
    # captured API mock layer, keyed by the path they take in the project
    # ("server/app.py", "mock/api.json"). Stored apart from `pages` because
    # these are not crawled pages and are never regenerated one route at a
    # time; the code map carries them under `GENERATED_FILE_PREFIX`.
    generated_files: Dict[str, str] = field(default_factory=lambda: cast(Dict[str, str], {}))
    phase: str = "crawling"
    error: str = ""
    created_at: float = 0.0
    updated_at: float = 0.0

    def page(self, path: str) -> ClonePage:
        existing = self.pages.get(path)
        if existing is None:
            existing = ClonePage(path=path)
            self.pages[path] = existing
        return existing

    def code_map(self) -> Dict[str, str]:
        """The run's output in the shape the frontend consumes."""
        code: Dict[str, str] = {}
        if self.portal:
            code["project-structure"] = self.portal
        for path, page in self.pages.items():
            if page.code:
                code[path] = page.code
        if self.database_schema:
            code["database-schema"] = self.database_schema
        for path, content in self.generated_files.items():
            code[f"{GENERATED_FILE_PREFIX}{path}"] = content
        return code

    def to_json(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "base_url": self.base_url,
            "stack": self.stack,
            "params": self.params,
            "llm": _redact_llm(self.llm),
            "crawl": crawl_result_to_json(self.crawl) if self.crawl else None,
            "pages": {path: page.to_json() for path, page in self.pages.items()},
            "portal": self.portal,
            "database_schema": self.database_schema,
            "generated_files": self.generated_files,
            "phase": self.phase,
            "error": self.error,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


def _redact_llm(llm: Dict[str, Any]) -> Dict[str, Any]:
    """Store which provider/model answered, never the key that paid for it."""
    return {key: value for key, value in llm.items() if "key" not in key.lower()}


def crawl_result_to_json(crawl: CrawlResult) -> Dict[str, Any]:
    return {
        "base_url": crawl.base_url,
        "pages": [
            {
                "url": page.url,
                "path": page.path,
                "title": page.title,
                "html": page.html,
                "screenshot": page.screenshot,
                "status_code": page.status_code,
                "links": page.links,
                "hash_routes": page.hash_routes,
                "pushed_routes": page.pushed_routes,
                "states": page.states,
                "embedded": page.embedded,
                "forms": page.forms,
                "navigation": page.navigation,
                "images": page.images,
                "videos": page.videos,
                "media": page.media,
                "design": page.design,
                "meta": page.meta,
                "screenshot_file": page.screenshot_file,
                "blocked": page.blocked,
                "stylesheets": page.stylesheets,
                "scripts": page.scripts,
                "depth": page.depth,
            }
            for page in crawl.pages
        ],
        "site_structure": crawl.site_structure,
        "design_tokens": crawl.design_tokens,
        "error": crawl.error,
    }


def _json_dict(value: Any) -> Dict[str, Any]:
    """A JSON object from parsed data, or an empty one."""
    return dict(value) if isinstance(value, dict) else {}


def _json_list(value: Any) -> List[Any]:
    """A JSON array from parsed data, or an empty one."""
    return list(value) if isinstance(value, list) else []


def _json_str_map(value: Any) -> Dict[str, str]:
    """A JSON object of strings, or an empty one.

    A stored run is written by one run of this code and read by another, so
    anything that is not a plain string is dropped rather than carried through
    as a value the callers expect to be text.
    """
    if not isinstance(value, dict):
        return {}
    entries = cast(Dict[str, Any], value)
    return {
        str(path): cast(str, content)
        for path, content in entries.items()
        if isinstance(content, str) and isinstance(path, str)
    }


def crawl_result_from_json(data: Optional[Dict[str, Any]]) -> Optional[CrawlResult]:
    if not data:
        return None
    pages: List[CrawlPage] = [
        CrawlPage(
            url=str(page.get("url", "")),
            path=str(page.get("path", "")),
            title=str(page.get("title", "")),
            html=str(page.get("html", "")),
            screenshot=str(page.get("screenshot", "")),
            status_code=int(page.get("status_code", 200) or 200),
            links=_json_list(page.get("links")),
            hash_routes=_json_list(page.get("hash_routes")),
            pushed_routes=_json_list(page.get("pushed_routes")),
            states=_json_list(page.get("states")),
            embedded=_json_dict(page.get("embedded")),
            forms=_json_list(page.get("forms")),
            navigation=_json_list(page.get("navigation")),
            images=_json_list(page.get("images")),
            videos=_json_list(page.get("videos")),
            media=_json_dict(page.get("media")),
            design=_json_dict(page.get("design")),
            meta=_json_dict(page.get("meta")),
            screenshot_file=str(page.get("screenshot_file", "")),
            blocked=bool(page.get("blocked", False)),
            stylesheets=_json_list(page.get("stylesheets")),
            scripts=_json_list(page.get("scripts")),
            depth=int(page.get("depth", 0) or 0),
        )
        for page in _json_list(data.get("pages"))
        if isinstance(page, dict)
    ]
    error = data.get("error")
    return CrawlResult(
        base_url=str(data.get("base_url", "")),
        pages=pages,
        site_structure=_json_dict(data.get("site_structure")),
        design_tokens=_json_dict(data.get("design_tokens")),
        error=str(error) if isinstance(error, str) else None,
    )


def run_from_json(data: Dict[str, Any]) -> CloneRun:
    raw_crawl = data.get("crawl")
    raw_pages: Dict[str, Any] = _json_dict(data.get("pages"))
    return CloneRun(
        run_id=str(data.get("run_id", "")),
        base_url=str(data.get("base_url", "")),
        stack=str(data.get("stack", "")),
        params=_json_dict(data.get("params")),
        llm=_json_dict(data.get("llm")),
        crawl=(
            crawl_result_from_json(raw_crawl) if isinstance(raw_crawl, dict) else None
        ),
        pages={
            str(path): ClonePage.from_json(page)
            for path, page in raw_pages.items()
            if isinstance(page, dict)
        },
        portal=str(data.get("portal", "")),
        database_schema=str(data.get("database_schema", "")),
        generated_files=_json_str_map(data.get("generated_files") or data.get("server_files")),
        phase=str(data.get("phase", "crawling")),
        error=str(data.get("error", "")),
        created_at=float(data.get("created_at", 0.0) or 0.0),
        updated_at=float(data.get("updated_at", 0.0) or 0.0),
    )


def new_run_id() -> str:
    return f"{time.strftime('%Y%m%d-%H%M%S')}-{uuid.uuid4().hex[:8]}"


def run_dir(run_id: str) -> Path:
    """Directory of one run, refusing anything the store did not mint.

    Silently stripping bad characters would let a crafted id resolve to a
    different run ("../a" becoming "a"), so unknown shapes are rejected
    outright rather than normalised.
    """
    if not run_id or not RUN_ID_RE.match(run_id):
        raise ValueError("Invalid clone run id")
    root = CLONE_RUNS_DIR.resolve()
    target = (root / run_id).resolve()
    try:
        target.relative_to(root)
    except ValueError as exc:
        raise ValueError("Invalid clone run id") from exc
    return target


def save_run(run: CloneRun, prune: bool = True) -> None:
    """Write a run to disk.

    `prune` can be turned off on the hot path: saving after every finished
    page would otherwise re-read every stored run's metadata (each one
    carrying a full crawl) once per page.
    """
    run.updated_at = time.time()
    if not run.created_at:
        run.created_at = run.updated_at
    directory = run_dir(run.run_id)
    directory.mkdir(parents=True, exist_ok=True)
    # Write to a sibling first so a crash mid-write cannot leave a truncated
    # run.json that fails to parse on the next read.
    target = directory / RUN_FILE
    tmp = directory / f"{RUN_FILE}.tmp"
    tmp.write_text(
        json.dumps(run.to_json(), ensure_ascii=False),
        encoding="utf-8",
    )
    os.replace(tmp, target)
    if prune:
        prune_runs()


def read_run_file(path: Path) -> Optional[Dict[str, Any]]:
    """Read one run.json, or None when it is missing, broken or not an object.

    The cast is explicit because a JSON object is only known to be a dict at
    runtime; the callers treat its values as untyped, which is what `Any`
    means here.
    """
    try:
        parsed: Any = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if isinstance(parsed, dict):
        return cast(Dict[str, Any], parsed)
    return None


def load_run(run_id: str) -> Optional[CloneRun]:
    try:
        path = run_dir(run_id) / RUN_FILE
    except ValueError:
        return None
    if not path.is_file():
        return None
    data = read_run_file(path)
    if data is None:
        return None
    try:
        return run_from_json(data)
    except (TypeError, ValueError):
        return None


def delete_run(run_id: str) -> bool:
    try:
        directory = run_dir(run_id)
    except ValueError:
        return False
    if not directory.is_dir():
        return False
    shutil.rmtree(directory, ignore_errors=True)
    return True


def list_runs(limit: int = 50) -> List[Dict[str, Any]]:
    """Summaries of stored runs, newest first, for the clone library."""
    if not CLONE_RUNS_DIR.is_dir():
        return []
    summaries: List[Dict[str, Any]] = []
    for directory in CLONE_RUNS_DIR.iterdir():
        if not directory.is_dir():
            continue
        path = directory / RUN_FILE
        if not path.is_file():
            continue
        data = read_run_file(path)
        if data is None:
            continue
        pages: Dict[str, Any] = _json_dict(data.get("pages"))
        page_list: List[Dict[str, Any]] = [
            page for page in pages.values() if isinstance(page, dict)
        ]
        scored = [
            float(page["fidelity"])
            for page in page_list
            if isinstance(page.get("fidelity"), (int, float))
        ]
        summaries.append(
            {
                "runId": data.get("run_id", directory.name),
                "baseUrl": data.get("base_url", ""),
                "stack": data.get("stack", ""),
                "phase": data.get("phase", ""),
                "error": data.get("error", ""),
                "createdAt": data.get("created_at", 0.0),
                "updatedAt": data.get("updated_at", 0.0),
                "pageCount": len(pages),
                "pagesComplete": sum(
                    1 for page in page_list if page.get("status") == COMPLETE
                ),
                "pagesFailed": sum(
                    1 for page in page_list if page.get("status") == FAILED
                ),
                "meanFidelity": sum(scored) / len(scored) if scored else None,
            }
        )
    summaries.sort(
        key=lambda item: float(item.get("updatedAt") or 0.0),
        reverse=True,
    )
    return summaries[:limit]


def prune_runs(max_runs: int = MAX_RUNS, max_age: float = MAX_RUN_AGE_SECONDS) -> int:
    """Drop the oldest and the expired runs. Returns how many were removed."""
    if not CLONE_RUNS_DIR.is_dir():
        return 0

    now = time.time()
    entries: List[tuple[float, Path]] = []
    for directory in CLONE_RUNS_DIR.iterdir():
        if not directory.is_dir():
            continue
        path = directory / RUN_FILE
        if not path.is_file():
            continue
        data = read_run_file(path)
        updated = 0.0
        if data is not None:
            try:
                updated = float(data.get("updated_at", 0.0) or 0.0)
            except (TypeError, ValueError):
                updated = 0.0
        entries.append((updated, directory))

    entries.sort(key=lambda entry: entry[0], reverse=True)
    removed = 0
    for index, (updated, directory) in enumerate(entries):
        # updated == 0 means unreadable: it cannot be resumed and is not shown
        # in the library either, so it is safe to drop.
        expired = True if not updated else (now - updated) > max_age
        if expired or index >= max_runs:
            shutil.rmtree(directory, ignore_errors=True)
            removed += 1
    return removed
