"""Headless site-cloning agent.

Crawls a website, regenerates every page as a self-contained file with an
LLM, and writes the project straight into a local folder -- no UI needed.

Usage:
    cd backend
    poetry run python clone_site.py https://example.com --out ../cloned-site \
        --base-url https://api.provider.com/v1 --api-key sk-... --model gpt-4o

Providers:
    custom      OpenAI-compatible endpoint (--base-url, --api-key, --model)
    openai      official API (uses OPENAI_API_KEY / OPENAI_BASE_URL env)
    anthropic   ANTHROPIC_API_KEY
    gemini      GEMINI_API_KEY
    openrouter  OPENROUTER_API_KEY (--model optional)
    mock        offline stub, for pipeline testing without any key

Output layout:
    index.html        first page of the crawl
    <path>.html       every other crawled page, mapped from its URL path
    portal.html       generated landing page linking the whole site
    database-schema.sql  only with --generate-database
    README.md
"""

from __future__ import annotations

import argparse
import asyncio
import posixpath
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

from config import (
    ANTHROPIC_API_KEY,
    GEMINI_API_KEY,
    OPENAI_API_KEY,
    OPENAI_BASE_URL,
    OPENROUTER_API_KEY,
)
from crawler.crawler import CrawlResult, SiteCrawler
from prompts.url_to_code_prompts import (
    build_database_schema_prompt,
    build_page_prompt,
    build_project_structure_prompt,
)
from routes.local_project import _safe_relative_parts, build_readme
from routes.url_to_code import (
    UrlToCodeParams,
    _clean_llm_output,
    _llm_config_for,
)
from llm_http import LlmConfig, ProviderError, complete

MAX_CONCURRENT_GENERATIONS = 3

PORTAL_FILENAME = "portal.html"
INDEX_FILENAME = "index.html"
SCHEMA_FILENAME = "database-schema.sql"

MOCK_HTML = (
    "<!DOCTYPE html>\n"
    '<html lang="en">\n'
    '<head><meta charset="UTF-8"><title>Mock clone</title></head>\n'
    "<body>\n"
    "  <nav><a href=\"/\">Home</a></nav>\n"
    "  <main><h1>Mock clone</h1><p>Offline stub generated by clone_site.py.</p></main>\n"
    "</body>\n"
    "</html>"
)


def page_path_to_filename(path: str, fallback_index: int) -> str:
    """Map a crawled page path to a file name inside the output folder.

    "/" becomes index.html, "/about" becomes about.html, nested paths keep
    their directory structure. Unusable paths fall back to page_<n>.html so
    one weird URL can never abort the whole run.
    """
    cleaned = (path or "").strip()
    if cleaned in ("", "/"):
        return INDEX_FILENAME
    try:
        relative = _safe_relative_parts(cleaned)
    except ValueError:
        return f"page_{fallback_index}.html"

    name = str(relative).replace("\\", "/")
    if name.endswith(".html"):
        return name
    return f"{name}.html"


def relative_link_map(filenames: Dict[str, str], current: str) -> Dict[str, str]:
    """Point every crawled path at its file, relative to the page `current`.

    Pages are written into nested folders ("blog/post.html"), and a link has
    to work when the folder is opened straight from disk.
    """
    base = posixpath.dirname(current) or "."
    return {
        path: posixpath.relpath(name, base) for path, name in filenames.items()
    }


def resolve_provider(args: argparse.Namespace) -> tuple[str, str | None, str | None]:
    """Return (provider, api_key, base_url) from flags, then environment."""
    if args.provider == "mock":
        return ("mock", None, None)

    # An explicit provider flag wins; otherwise a base URL implies a
    # custom OpenAI-compatible endpoint; otherwise fall back to env keys.
    if args.provider:
        provider = args.provider
    elif args.base_url:
        provider = "custom"
    else:
        params = UrlToCodeParams(
            url=args.url,
            openai_api_key=OPENAI_API_KEY,
            anthropic_api_key=ANTHROPIC_API_KEY,
            gemini_api_key=GEMINI_API_KEY,
            openrouter_api_key=OPENROUTER_API_KEY,
        )
        provider = _llm_config_for(params).provider

    api_key = args.api_key
    base_url = args.base_url

    if provider == "openai":
        api_key = api_key or OPENAI_API_KEY
        base_url = base_url or OPENAI_BASE_URL
    elif provider == "anthropic":
        api_key = api_key or ANTHROPIC_API_KEY
    elif provider == "gemini":
        api_key = api_key or GEMINI_API_KEY
    elif provider == "openrouter":
        api_key = api_key or OPENROUTER_API_KEY

    if provider != "mock" and not api_key and provider != "custom":
        raise SystemExit(
            f"No API key for provider '{provider}'. "
            "Pass --api-key or set the provider's environment variable."
        )
    if provider == "custom" and not base_url:
        raise SystemExit("Provider 'custom' requires --base-url.")
    if provider == "custom" and not api_key:
        api_key = "no-key"

    return (provider, api_key, base_url)


async def call_llm(
    provider: str,
    messages: List[Dict[str, str]],
    api_key: str | None,
    base_url: str | None,
    model: str | None,
) -> str | None:
    if provider == "mock":
        return MOCK_HTML

    system = next((m["content"] for m in messages if m["role"] == "system"), "")
    user = next((m["content"] for m in messages if m["role"] != "system"), "")

    if provider == "openai" and model and base_url:
        # Explicit model plus endpoint: treat it as an OpenAI-compatible
        # server so the model choice is honoured.
        provider = "custom"

    if provider not in ("custom", "openai", "anthropic", "gemini", "openrouter"):
        raise SystemExit(f"Unknown provider: {provider}")

    result = await complete(
        LlmConfig(
            provider=provider,
            model=model or "",
            api_key=api_key or ("no-key" if provider == "custom" else ""),
            base_url=base_url or "",
        ),
        system,
        user,
    )
    if not result.text and result.empty_reason:
        print(f"[CLONE] empty answer: {result.empty_reason}")
    return result.text


async def generate_one(
    page: Dict[str, Any],
    args: argparse.Namespace,
    provider: str,
    api_key: str | None,
    base_url: str | None,
    model: str | None,
    semaphore: asyncio.Semaphore,
    filenames: Dict[str, str] | None = None,
) -> Tuple[str, str]:
    """Generate code for one page; returns (filename, code)."""
    filename = page["_filename"]
    link_map = relative_link_map(filenames, filename) if filenames else None
    prompt_messages = build_page_prompt(
        page, args.stack, args.generate_database, link_map
    )
    messages = [
        {"role": "system", "content": prompt_messages[0]["content"]},
        {"role": "user", "content": "Generate the code now."},
    ]
    async with semaphore:
        completion = await call_llm(provider, messages, api_key, base_url, model)
    if not completion:
        raise RuntimeError(f"empty response for {page['path']}")
    return filename, _clean_llm_output(completion)


async def run(args: argparse.Namespace) -> int:
    provider, api_key, base_url = resolve_provider(args)
    print(
        f"[CLONE] provider={provider} model={args.model or '-'} "
        f"stack={args.stack} out={args.out}"
    )

    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    crawler = SiteCrawler(
        max_pages=args.max_pages,
        max_depth=args.max_depth,
        timeout=args.timeout,
    )
    async def on_progress(status: str, current: int, total: int) -> None:
        print(f"[CRAWL] {status} ({current}/{total})")

    crawler.set_progress_callback(on_progress)
    result: CrawlResult = await crawler.crawl(args.url)
    if result.error:
        print(f"[CLONE] Crawl failed: {result.error}", file=sys.stderr)
        return 1
    if not result.pages:
        print("[CLONE] Crawl returned no pages.", file=sys.stderr)
        return 1
    print(f"[CLONE] Crawled {len(result.pages)} pages.")

    # Bot-check interstitials ("Just a moment...") are not the site; cloning
    # them just writes a verification page to disk.
    crawled = [page for page in result.pages if not page.blocked]
    if not crawled:
        print(
            "[CLONE] Every page was a bot-check (Cloudflare) interstitial; "
            "nothing to clone.",
            file=sys.stderr,
        )
        return 1
    if len(crawled) < len(result.pages):
        print(f"[CLONE] Skipping {len(result.pages) - len(crawled)} bot-check pages.")
    result.pages = crawled

    pages: List[Dict[str, Any]] = []
    used_filenames: set[str] = set()
    for i, page in enumerate(result.pages):
        filename = page_path_to_filename(page.path, i)
        while filename in used_filenames:
            stem, dot, ext = filename.rpartition(".")
            filename = f"{stem}_2.{ext}" if dot else f"{filename}_2"
        used_filenames.add(filename)
        pages.append(
            {
                "url": page.url,
                "path": page.path,
                "title": page.title,
                "html": page.html,
                "screenshot": "",
                "forms": page.forms,
                "navigation": page.navigation,
                "images": page.images,
                "depth": page.depth,
                "_filename": filename,
            }
        )

    filenames: Dict[str, str] = {}
    for page in pages:
        filenames.setdefault(page["path"].rstrip("/") or "/", page["_filename"])

    written: dict[str, str] = {}

    # Landing page first; its failure should not block per-page generation.
    structure_prompt = build_project_structure_prompt(
        result, args.stack, args.generate_database, args.generate_auth
    )
    try:
        structure = await call_llm(
            provider,
            [
                {"role": "system", "content": structure_prompt},
                {"role": "user", "content": "Generate the code now."},
            ],
            api_key,
            base_url,
            args.model,
        )
        if structure:
            written[PORTAL_FILENAME] = _clean_llm_output(structure)
            print(f"[CLONE] portal page generated ({len(structure)} chars)")
        else:
            print("[CLONE] portal page came back empty; continuing with pages")
    except ProviderError as exc:
        print(f"[CLONE] Provider refused: {exc}", file=sys.stderr)
        return 1

    if args.generate_database:
        schema_prompt = build_database_schema_prompt(result, args.stack)
        try:
            schema = await call_llm(
                provider,
                [
                    {"role": "system", "content": schema_prompt},
                    {"role": "user", "content": "Generate the schema now."},
                ],
                api_key,
                base_url,
                args.model,
            )
            if schema:
                written[SCHEMA_FILENAME] = _clean_llm_output(schema)
        except ProviderError as exc:
            print(f"[CLONE] Schema generation failed: {exc}", file=sys.stderr)

    semaphore = asyncio.Semaphore(MAX_CONCURRENT_GENERATIONS)
    tasks = [
        generate_one(
            page, args, provider, api_key, base_url, args.model, semaphore, filenames
        )
        for page in pages
    ]
    results = await asyncio.gather(*tasks, return_exceptions=True)

    failed = 0
    for page, outcome in zip(pages, results):
        if isinstance(outcome, BaseException):
            failed += 1
            print(f"[CLONE] FAILED {page['path']}: {outcome}", file=sys.stderr)
            continue
        filename, code = outcome
        written[filename] = code
        print(f"[CLONE] done {page['path']} -> {filename} ({len(code)} chars)")

    # The first crawled page is the site's real entry; mirror it as
    # index.html so the folder opens like the original site.
    first = next((p for p in pages if p["depth"] == 0), pages[0])
    if first["_filename"] in written and INDEX_FILENAME not in written:
        written[INDEX_FILENAME] = written[first["_filename"]]

    if not any(written.values()):
        print("[CLONE] Nothing was generated.", file=sys.stderr)
        return 1

    for filename, code in written.items():
        target = out_dir / _safe_relative_parts(filename)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(code, encoding="utf-8")

    readme_names = [
        name
        for name in written
        if not name.startswith("assets/")
    ]
    (out_dir / "README.md").write_text(
        build_readme(args.site_name or "Cloned site", sorted(readme_names)),
        encoding="utf-8",
    )

    print(
        f"[CLONE] Finished: {len(written)} files written to {out_dir} "
        f"({failed} pages failed)."
    )
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Clone a website into a local folder with an LLM."
    )
    parser.add_argument("url", help="Site to crawl, e.g. https://example.com")
    parser.add_argument("--out", required=True, help="Output folder for the clone")
    parser.add_argument(
        "--stack",
        default="html_tailwind",
        help="html_tailwind | html_css | react_tailwind | bootstrap | vue_tailwind | ionic_tailwind",
    )
    parser.add_argument("--max-pages", type=int, default=10)
    parser.add_argument("--max-depth", type=int, default=2)
    parser.add_argument("--timeout", type=int, default=15, help="Per-page load timeout (s)")
    parser.add_argument(
        "--provider",
        choices=["custom", "openai", "anthropic", "gemini", "openrouter", "mock"],
        default=None,
        help="LLM provider; defaults to custom when --base-url is given",
    )
    parser.add_argument("--base-url", default=None, help="OpenAI-compatible endpoint")
    parser.add_argument("--api-key", default=None)
    parser.add_argument("--model", default=None)
    parser.add_argument("--site-name", default=None, help="Name used in the README")
    parser.add_argument("--generate-database", action="store_true")
    parser.add_argument("--generate-auth", action="store_true")
    return parser.parse_args(argv)


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(run(parse_args())))
    except KeyboardInterrupt:
        print("\n[CLONE] Interrupted.")
        sys.exit(130)
