import { Commit } from "../components/commits/types";
import { applyFileOverrides, buildFrameworkProjectFiles } from "./frameworkProject";

/**
 * Turning a generated code map into a project's files.
 *
 * Kept apart from `localProject.ts` because that module reaches for the
 * backend URL and the File System Access API at import time, which makes it
 * unusable outside a browser. Nothing here touches the network or the DOM, so
 * the layout rules — which the editor, the ZIP and the folder writer all have
 * to agree on — can be tested directly.
 */

/**
 * Files the run produced beyond its pages - the generated server and the
 * captured API mock layer - travel in the same code map as the pages, under
 * this prefix and then their own project path. One prefix for both kinds so
 * there is a single rule for "not a page"; keep it in step with
 * `GENERATED_FILE_PREFIX` in backend/clone_runs.py.
 */
export const GENERATED_FILE_PREFIX = "file:";

export function generatedPathFor(key: string): string | null {
  const path = key.slice(GENERATED_FILE_PREFIX.length);
  // A key that does not name a file inside the project is refused rather
  // than written: the path comes from the backend, but nothing should be
  // able to place a file outside the folder the user is about to save.
  if (!path || path.startsWith("/") || path.includes("..") || path.includes("\\")) {
    return null;
  }
  return path;
}

export interface ProjectFile {
  path: string;
  content: string;
  /**
   * The code-map key this file was generated from: a page path ("/about"), or
   * "project-structure" / "database-schema" for the portal and the SQL schema.
   * Kept so a page can be found again by route - the editor, the visual check
   * and a regeneration all address pages by route, not by file name.
   * Absent for scaffolding the run adds on its own (README, package.json).
   */
  pageKey?: string;
}

/** Best-effort site name used for folder naming and the README. */
export function siteNameFromCode(code: Record<string, string>): string {
  const html =
    code["project-structure"] ??
    Object.values(code).find((value) => value && value.trim()) ??
    "";
  const match = html.match(/<title[^>]*>([^<]{1,80})<\/title>/i);
  return match ? match[1].trim() : "cloned-site";
}

export function slugifyPagePath(raw: string): string {
  const cleaned = raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return cleaned || "page";
}

export function buildReadme(siteName: string, fileNames: string[], hasServer = false): string {
  const list = fileNames.map((name) => `- \`${name}\``).join("\n");
  const server: string[] = [];
  if (hasServer) {
    server.push(
      `\`\`\`bash
cd server
pip install -r requirements.txt
python -m uvicorn app:app --reload
\`\`\``,
      "",
      "The pages are served from this folder, and the API is at `/docs`. Everything",
      "is stored in `server/clone.db`, created on first run and kept across restarts."
    );
  }
  if (fileNames.some((name) => name.startsWith("mock/"))) {
    server.push(
      "",
      "The original site filled its pages by calling an API. The answers it gave",
      "were recorded while it was crawled and are in `mock/`. Add this to any page",
      "before the scripts that load data:",
      "",
      "```html",
      '<script src="/mock/mock.js"></script>',
      "```"
    );
  }
  const run = server.length > 0
    ? server.join("\n")
    : `\`\`\`bash
python -m http.server 8080
\`\`\``;
  return `# ${siteName}

Generated by UrlToCode.

## Run locally

${run}

## Files

${list}
`;
}

/**
 * Maps the url-to-code output (`{ "project-structure": html, "/about": html, ... }`)
 * onto a flat file tree rooted at `index.html`.
 *
 * `overrides` carries hand edits made in the editor, keyed by the project-file
 * path the user saw, so what is saved to disk is what the editor shows.
 */
export function buildProjectFiles(
  code: Record<string, string>,
  siteName?: string,
  overrides: Record<string, string> = {}
): ProjectFile[] {
  const keys = Object.keys(code).filter((key) => code[key] && code[key].trim());
  if (keys.length === 0) return [];

  // Next.js / React clones are laid out as a real project, not HTML files.
  const frameworkFiles = buildFrameworkProjectFiles(code, siteName ?? "Generated site");
  if (frameworkFiles) {
    return applyFileOverrides(frameworkFiles, overrides);
  }

  const files: ProjectFile[] = [];
  const usedNames = new Set<string>();
  const portalKey = keys.includes("project-structure") ? "project-structure" : null;

  const uniqueName = (base: string) => {
    let name = base;
    let counter = 2;
    while (usedNames.has(name)) {
      name = base.replace(/(\.[a-z0-9]+)?$/i, (ext) => `-${counter}${ext ?? ""}`);
      counter += 1;
    }
    usedNames.add(name);
    return name;
  };

  // The crawled root page is the clone's real home page, so it owns
  // index.html. Generated pages link to each other by these names
  // (backend/prompts/url_to_code_prompts.py `page_filename`).
  const rootKey = keys.includes("/") ? "/" : null;
  if (rootKey) {
    files.push({
      path: uniqueName("index.html"),
      content: code[rootKey],
      pageKey: rootKey,
    });
  }

  for (const key of keys) {
    if (key === portalKey || key === rootKey) continue;
    if (key === "database-schema") {
      files.push({
        path: "database-schema.sql",
        content: code[key],
        pageKey: key,
      });
      continue;
    }
    // A generated file keeps its own place in the project rather than being
    // named like a page: flattening `server/app.py` would lose the layout
    // the README's `cd server` depends on.
    if (key.startsWith(GENERATED_FILE_PREFIX)) {
      const path = generatedPathFor(key);
      if (path) {
        files.push({ path, content: code[key], pageKey: key });
      }
      continue;
    }
    files.push({
      path: uniqueName(`${slugifyPagePath(key)}.html`),
      content: code[key],
      pageKey: key,
    });
  }

  // The portal is a generated overview, not part of the copy: it only takes
  // index.html when the crawl has no root page.
  if (portalKey) {
    const portalName =
      rootKey || usedNames.has("index.html") ? uniqueName("portal.html") : uniqueName("index.html");
    files.push({ path: portalName, content: code[portalKey], pageKey: portalKey });
  }

  files.push({
    path: "README.md",
    content: buildReadme(
      siteName ?? "Generated site",
      files.map((f) => f.path),
      files.some((f) => f.path.startsWith("server/"))
    ),
  });
  return applyFileOverrides(files, overrides);
}

/**
 * The project file that holds a given page, or null when the project has none.
 *
 * The file name is not derivable from the route by the caller alone - the
 * portal takes `index.html` only when the crawl had no root page, and every
 * other file goes through the same collision-avoiding naming as the ZIP - so
 * the answer comes from the layout itself rather than from a second guess at
 * the naming rules.
 */
export function projectFileForPage(
  code: Record<string, string>,
  pageKey: string
): string | null {
  for (const file of buildProjectFiles(code, siteNameFromCode(code))) {
    if (file.pageKey === pageKey) return file.path;
  }
  return null;
}

/**
 * Rebuilds the generated-code map from project commits. Cloned pages are
 * stored as `code_create` commits whose label is the page path ("Portal" for
 * the landing page).
 */
export function buildCodeMapFromCommits(
  commits: Record<string, Commit>
): Record<string, string> {
  const code: Record<string, string> = {};
  for (const commit of Object.values(commits)) {
    if (commit.type !== "code_create") continue;
    const variantCode = commit.variants[commit.selectedVariantIndex]?.code;
    if (!variantCode || !variantCode.trim()) continue;
    const key = commit.label === "Portal" ? "project-structure" : commit.label ?? "/";
    code[key] = variantCode;
  }
  return code;
}
